### ISSUE TITLE
Missing latest tag on docker hub

### ISSUE THREAD

**Issue by feldsam** [funkyfuture/deck-chores#49]
Hello, few days ago `latest` was removed from docker hub. Would you please add the latest stable version as `latest` tag on docker hub? Thank you.

**Comment by funkyfuture** [comment]
ciao, yes, i deleted that tag b/c after releasing the `1.0-rc1` image the `latest` tag pointed to something older.

adding to create a manifest tagged `latest` for the latest release is probably easy to do. but in the strictest sense there hasn't been a stable release yet, but the upcoming `1.0` will be. since i also don't plan to add new features after that atm, i also don't see no need for distinguishing stable and unstable releases.

**Comment by feldsam** [comment]
ok, I understand, but in that case, you should update docs too, to include tag. Because by default docker looks for `latest` tag. So you effectively broken all deployments without tag :)

**Comment by funkyfuture** [comment]
can you be more specific what you mean with "update docs too, to include tag"?

the default value of `latest` as tag was recognized as design bug by the Docker community and vendor quiet early (there are enough elaborations on that over the www) and i really don't want to enable people to use bad practices. what i plan to facilitate is to provide tags for the scopes of major, minor and patch levels within the concept of semantic versioning, so people can rely on a compatible and up-to-date image. so, would you be suggesting to note that in the docs?

**Comment by feldsam** [comment]
Good to know about bad design, it is new for me. Then ok, no problem at all. Anyway, thanks for good job you do on this project!

**Comment by funkyfuture** [comment]
i pushed new tags to the Docker registry. does this work for you?

**Comment by ddimick** [comment]
I'm able to pull with the new tags.

To @feldsam's point, the example docker-compose config in the documentation is no longer valid as it doesn't specify a tag and, for better or for worse, docker still looks for latest in that case.

**Comment by funkyfuture** [comment]
thanks for the notice. i amened it w/ 3bc39b88501c3804c99d55080af5284a7ed35b80

**Comment by russ-ab** [comment]
@funkyfuture Still not working, (2020-03-04) 

```
> docker pull funkyfuture/deck-chores
Using default tag: latest
Error response from daemon: manifest for funkyfuture/deck-chores:latest not found: manifest unknown: manifest unknown
```

With using tag :1 all goes good.

``` 
> docker pull funkyfuture/deck-chores:1
1: Pulling from funkyfuture/deck-chores
c9b1b535fdd9: Pull complete
2cc5ad85d9ab: Pull complete
53a2fca3c2ea: Pull complete
30fce49de8b1: Pull complete
ca406aaf66e0: Pull complete
c27a0a1eaf84: Pull complete
eab142ad0b0b: Pull complete                                                                                                          Digest: sha256:bf32f06bc9dd06d890473b77ec599bc3a76679944c95591d7afb8858cdfe3f3e
Status: Downloaded newer image for funkyfuture/deck-chores:1
docker.io/funkyfuture/deck-chores:1
```
